# Site settings
name: Graham Vriend
email: grvriend@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, IT Technical Lead, "
skills: "IT Technical Lead (Software Development) Developing remotely in Salem, OR"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/grvriend/
  - title: medium
    url: https://medium.com/@grvriend
  - title: twitter
    url: https://twitter.com/grvriend
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  text-color: 54575A
  primary: F8F7F6
  primary-rgb: "248, 247, 246"
  secondary: FFFFFF
  secondary-dark: FAB131
  section-tout: F8F7F6



# Build settings
markdown: kramdown
permalink: pretty
